### ISSUE TITLE
Zap handling of ClassName contains '$'

### ISSUE THREAD

**Issue by cmeng-git** [pantsbuild/jarjar#23]
How to zap a jar package with classname containing '$' as shown below
org.example.XMPPTCPConnection$1.class 
org.example.XMPPTCPConnection$2.class
org.example.XMPPTCPConnection$3.class 
org.example.XMPPTCPConnection$PacketReader$1.class

But need to keep org.example.XMPPTCPConnectionConfiguration.class

zap  pattern: "org.example.XMPPTCPConnection$**" does not work
zap  pattern: "org.example.XMPPTCPConnection**" removes all  including org.example.XMPPTCPConnectionConfiguration.class

Appreciate any help

**Comment by jsirois** [comment]
Bear in mind, the pantsbuild project does not support jarjar for independent use, we just grabbed a copy of the project from https://code.google.com/archive/p/jarjar/ before it shut down to use internally in https://github.com/pantsbuild/pants.

That said, have you tried either:
1. enumerating the full list of zaps? In your example above this would be 4 items, `org.example.XMPPTCPConnection$1`, etc...
2. using a rename rule to rename `org.example.XMPPTCPConnectionConfiguration`

I'm pretty positive 2 will work since renames are processed 1st.  Clearly it might have impact on your code if your code uses that class.  If you use 3rdparty code that uses that class, things get messier to be sure. In that case you might just run jarjar twice, 1st rename + zap, 2nd rename back to original name.

**Comment by cmeng-git** [comment]
Many thanks.

Method #1 does not work, as it seems jarjar treats '$' as special and ignores it even I escape with .
I did thought of method #2 but decided not to use it  as it makes build code messy.

To solve the problem, currently I just zap all the unwanted classes in the original jar package.
I hope someone in the community knows a way to do it in a cleaner way.

Thanks again for the proposal

**Comment by alexarchambault** [comment]
I've been running into that too, while trying to shade classes generated by the scala compiler (with `$` in their names). This originates from the `$` in class names not being escaped before being passed to `java.util.regex.Pattern.compile` around [here](https://github.com/pantsbuild/jarjar/blob/57845dc73d3e2c9b916ae4a788cfa12114fd7df1/src/main/java/org/pantsbuild/jarjar/Wildcard.java#L48).
