### ISSUE TITLE
support JDK11 class files (JEP 181: Nest-Based Access Control)

### ISSUE THREAD

**Issue by xuwei-k** [pantsbuild/jarjar#39]
- http://openjdk.java.net/jeps/181
- https://github.com/pantsbuild/jarjar/blob/org.pantsbuild-jarjar-1.6.6/lib/BUILD#L1-L13
- https://gitlab.ow2.org/asm/asm/blob/ASM_6_2_1/asm/src/main/java/org/objectweb/asm/ClassVisitor.java#L157
- https://github.com/sbt/sbt-assembly/issues/343

**Comment by jsirois** [comment]
Pants will need JDK 11 support, so this is a legitimate issue - but I do hope it's clear that this clone/fork/resurrection of jarjar is intended for Pants use only as things stand. SBT can of course use this open source code, but just to be clear that we won't be working on this in all likelihood until we have a driving use case just due to time constraints. Is this something you were thinking of working on?
